### ISSUE TITLE
NixOS, LTO, qmake ltcg

### ISSUE THREAD

**Issue by deliciouslytyped** [blueprint-freespeech/ricochet-refresh#104]
I don't have a good understanding of low level linker issues, however the current way LTO is set up in ricochet-refresh causes problems during source builds on my Linux distribution, which is NixOS. (I think.)

I haven't been able to figure out the root cause(es) yet, however some research suggests that the best way to enable LTO with QMake is not to pass `-lto` as flags, but to add the `ltcg` parameter to `CONFIG`. [1] [2]

[1] https://www.qt.io/blog/2019/01/02/qt-applications-lto
[2] https://doc.qt.io/qt-5/qmake-variable-reference.html

The following seems at least somewhat relevant, and is how I found `ltcg` as a relevant term:
https://code.qt.io/cgit/qt/qtbase.git/commit/?id=0f569f5900ea4cf3af551c90f79b80fc78dce9bf -> https://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/common/gcc-base.conf?id=0f569f5900ea4cf3af551c90f79b80fc78dce9bf

cc @pospeselr

**Comment by pospeselr** [comment]
It has been awhile since I got ricochet-build working ( https://github.com/blueprint-freespeech/ricochet-build ) but if IIRC the link-time-optimization flags used by openssl and Qt to enable static builds (linking required Qt runtime into final bin, rather than shipping Qt libs) are incompatible, hence the clusterfuck there.

Long term we would like to dump Qt entirely and switch to WxWidgets, but only so much time in a day.

**Comment by m-simonelli** [comment]
No longer relevant as of 9e8a5ed7bdf10776b64679a813a299fb2ff68484
